image: ondrejsika/ci

stages:
    - build
    - test
    - deploy dev
    - deploy prod

variables:
    IMAGE: $CI_REGISTRY_IMAGE
    TAG: $CI_COMMIT_REF_SLUG

before_script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD

build:
    stage: build
    variables:
        COMPOSE_FILE: docker-compose.yml:docker-compose-test.yml
    script:
        - docker-compose build
        - docker-compose push

test:
    stage: test
    variables:
        COMPOSE_FILE: docker-compose.yml:docker-compose-test.yml
        COMPOSE_PROJECT_NAME: $CI_JOB_ID
    script:
        - docker-compose pull
        - docker-compose up --no-build tests
    after_script:
        - docker-compose down

.dev: &dev
    stage: deploy dev
    variables:
        DOCKER_HOST: tcp://$BASE_HOST:2376
        HOST: $CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG.$BASE_HOST
        COMPOSE_PROJECT_NAME: $CI_COMMIT_REF_SLUG
        COMPOSE_FILE: docker-compose.yml:docker-compose-traefik.yml

deploy dev:
    <<: *dev
    environment:
        name: $CI_COMMIT_REF_SLUG
        url: https://$CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG.$BASE_HOST
        on_stop: stop dev
    script:
        - docker-compose pull
        - docker-compose up -d --no-build
    after_script:
        - sleep 10 && curl -fsSL https://$CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG.$BASE_HOST

stop dev:
    when: manual
    <<: *dev
    environment:
        name: $CI_COMMIT_REF_SLUG
        action: stop
    script:
        - docker-compose down

deploy prod:
    only:
        - master
    stage: deploy prod
    variables:
        DOCKER_HOST: tcp://$BASE_HOST:2376
        HOST: $PRODUCTION_HOST
        COMPOSE_PROJECT_NAME: $CI_COMMIT_REF_SLUG
        COMPOSE_FILE: docker-compose.yml:docker-compose-traefik.yml
    environment:
        name: $PRODUCTION_HOST
        url: https://$PRODUCTION_HOST
        on_stop: stop dev
    script:
        - docker-compose pull
        - docker-compose up -d --no-build
    after_script:
        - sleep 10 && curl -fsSL https://$PRODUCTION_HOST