image: ondrejsika/ci

stages:
    - build
    - test
    - deploy dev
    - deploy prod

variables:
    IMAGE: $CI_REGISTRY_IMAGE
    TAG: $CI_COMMIT_REF_SLUG

before_script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD

build:
    stage: build
    script:
        - docker-compose build
        - docker-compose push