image: ondrejsika/ci

stages:
    - build
    - test
    - deploy dev
    - deploy prod

variables:
    IMAGE: $CI_REGISTRY_IMAGE
    TAG: $CI_COMMIT_REF_SLUG

before_script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD

build:
    stage: build
    variables:
        COMPOSE_FILE: docker-compose.yml:docker-compose-test.yml
    script:
        - docker-compose build
        - docker-compose push

test:
    stage: test
    variables:
        COMPOSE_FILE: docker-compose.yml:docker-compose-test.yml
        COMPOSE_PROJECT_NAME: $CI_JOB_ID
    script:
        - docker-compose pull
        - docker-compose up --no-build tests
        - docker-compose down
